Traceback (most recent call last):
  File "run.py", line 46, in <module>
    optimizer=optimizer, epoch=epoch)                ###logger added
  File "C:\Users\kevin\OneDrive\Documents\8th sem\Federated_Pneumonia\src\client\train.py", line 10, in train
    output = model(data)
  File "C:\Users\kevin\anaconda3\envs\fl\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\kevin\OneDrive\Documents\8th sem\Federated_Pneumonia\src\client\models.py", line 42, in forward
    x = self.model(x)
  File "C:\Users\kevin\anaconda3\envs\fl\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\kevin\anaconda3\envs\fl\lib\site-packages\torchvision\models\resnet.py", line 216, in forward
    return self._forward_impl(x)
  File "C:\Users\kevin\anaconda3\envs\fl\lib\site-packages\torchvision\models\resnet.py", line 204, in _forward_impl
    x = self.layer1(x)
  File "C:\Users\kevin\anaconda3\envs\fl\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\kevin\anaconda3\envs\fl\lib\site-packages\torch\nn\modules\container.py", line 100, in forward
    input = module(input)
  File "C:\Users\kevin\anaconda3\envs\fl\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\kevin\anaconda3\envs\fl\lib\site-packages\torchvision\models\resnet.py", line 109, in forward
    out = self.bn3(out)
  File "C:\Users\kevin\anaconda3\envs\fl\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\kevin\anaconda3\envs\fl\lib\site-packages\torch\nn\modules\batchnorm.py", line 107, in forward
    exponential_average_factor, self.eps)
  File "C:\Users\kevin\anaconda3\envs\fl\lib\site-packages\torch\nn\functional.py", line 1670, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 32.00 MiB (GPU 0; 2.00 GiB total capacity; 570.39 MiB already allocated; 0 bytes free; 594.00 MiB reserved in total by PyTorch)
