2021-01-11 23:17:20,515 INFO    MainThread:12524 [wandb_setup.py:_flush():70] setting env: {}
2021-01-11 23:17:20,516 INFO    MainThread:12524 [wandb_setup.py:_flush():70] multiprocessing start_methods=spawn
2021-01-11 23:17:20,516 INFO    MainThread:12524 [wandb_setup.py:_flush():70] setting login settings: {}
2021-01-11 23:17:20,516 INFO    MainThread:12524 [wandb_init.py:_log_setup():303] Logging user logs to C:\Users\kevin\OneDrive\Documents\8th sem\Federated_Pneumonia\src\aggregator\wandb\run-20210111_231720-2lj7b9tc\logs\debug.log
2021-01-11 23:17:20,516 INFO    MainThread:12524 [wandb_init.py:_log_setup():304] Logging internal logs to C:\Users\kevin\OneDrive\Documents\8th sem\Federated_Pneumonia\src\aggregator\wandb\run-20210111_231720-2lj7b9tc\logs\debug-internal.log
2021-01-11 23:17:23,630 INFO    MainThread:12524 [wandb_run.py:_console_start():1237] atexit reg
2021-01-11 23:17:23,632 INFO    MainThread:12524 [wandb_run.py:_redirect():1104] redirect: SettingsConsole.WRAP
2021-01-11 23:17:23,632 INFO    MainThread:12524 [wandb_run.py:_redirect():1135] Wrapping output streams.
2021-01-11 23:17:23,632 INFO    MainThread:12524 [wandb_run.py:_redirect():1151] Redirects installed.
2021-01-11 23:17:25,249 INFO    MainThread:12524 [wandb_run.py:_atexit_cleanup():1207] got exitcode: 3
2021-01-11 23:17:25,249 INFO    MainThread:12524 [wandb_run.py:_restore():1179] restore
2021-01-11 23:17:25,254 INFO    MainThread:12524 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "6cc0f3c0c55e48b7bc79d1908ba86759"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 1152
      total_bytes: 1152
    }
  }
}

2021-01-11 23:17:27,256 INFO    MainThread:12524 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "441a1bd7f0474429984f425c370f887a"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 5177
      total_bytes: 5177
    }
  }
}

2021-01-11 23:17:29,261 INFO    MainThread:12524 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "291e8334a3a0473eb5280cca94d324e5"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 5177
      total_bytes: 5177
    }
  }
}

2021-01-11 23:17:30,424 INFO    MainThread:12524 [wandb_run.py:_show_files():1536] logging synced files
2021-01-11 23:17:30,448 INFO    MainThread:12524 [internal.py:handle_exit():138] Internal process exited
