2021-01-12 20:01:14,823 INFO    MainThread:3492 [wandb_setup.py:_flush():70] setting env: {}
2021-01-12 20:01:14,824 INFO    MainThread:3492 [wandb_setup.py:_flush():70] multiprocessing start_methods=spawn
2021-01-12 20:01:14,824 INFO    MainThread:3492 [wandb_setup.py:_flush():70] setting login settings: {}
2021-01-12 20:01:14,824 INFO    MainThread:3492 [wandb_init.py:_log_setup():303] Logging user logs to C:\Users\kevin\OneDrive\Documents\8th sem\Federated_Pneumonia\src\client\wandb\run-20210112_200114-nqo5eis9\logs\debug.log
2021-01-12 20:01:14,824 INFO    MainThread:3492 [wandb_init.py:_log_setup():304] Logging internal logs to C:\Users\kevin\OneDrive\Documents\8th sem\Federated_Pneumonia\src\client\wandb\run-20210112_200114-nqo5eis9\logs\debug-internal.log
2021-01-12 20:01:17,347 INFO    MainThread:3492 [wandb_run.py:_console_start():1237] atexit reg
2021-01-12 20:01:17,348 INFO    MainThread:3492 [wandb_run.py:_redirect():1104] redirect: SettingsConsole.WRAP
2021-01-12 20:01:17,348 INFO    MainThread:3492 [wandb_run.py:_redirect():1135] Wrapping output streams.
2021-01-12 20:01:17,349 INFO    MainThread:3492 [wandb_run.py:_redirect():1151] Redirects installed.
2021-01-12 20:01:29,688 INFO    MainThread:3492 [wandb_run.py:_atexit_cleanup():1207] got exitcode: 1
2021-01-12 20:01:29,688 INFO    MainThread:3492 [wandb_run.py:_restore():1179] restore
2021-01-12 20:01:29,706 INFO    MainThread:3492 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "ef2673256a4d4e35ab1aa28f24052f9d"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 1018
      total_bytes: 1018
    }
  }
}

2021-01-12 20:01:31,711 INFO    MainThread:3492 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "0984cde3b09b403a85e48f1bb8ccadf8"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 4836
      total_bytes: 4836
    }
  }
}

2021-01-12 20:01:33,713 INFO    MainThread:3492 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "d570f17ab3cc43a2a4d02ed918f41539"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 4836
      total_bytes: 4836
    }
  }
}

2021-01-12 20:01:34,785 INFO    MainThread:3492 [wandb_run.py:_show_files():1536] logging synced files
2021-01-12 20:01:34,801 INFO    MainThread:3492 [internal.py:handle_exit():138] Internal process exited
