2021-01-11 22:05:45,014 INFO    MainThread:16376 [wandb_setup.py:_flush():70] setting env: {}
2021-01-11 22:05:45,014 INFO    MainThread:16376 [wandb_setup.py:_flush():70] multiprocessing start_methods=spawn
2021-01-11 22:05:45,014 INFO    MainThread:16376 [wandb_setup.py:_flush():70] setting login settings: {}
2021-01-11 22:05:45,014 INFO    MainThread:16376 [wandb_init.py:_log_setup():303] Logging user logs to C:\Users\kevin\OneDrive\Documents\8th sem\Federated_Pneumonia\src\client\wandb\run-20210111_220545-167barst\logs\debug.log
2021-01-11 22:05:45,014 INFO    MainThread:16376 [wandb_init.py:_log_setup():304] Logging internal logs to C:\Users\kevin\OneDrive\Documents\8th sem\Federated_Pneumonia\src\client\wandb\run-20210111_220545-167barst\logs\debug-internal.log
2021-01-11 22:05:49,389 INFO    MainThread:16376 [wandb_run.py:_console_start():1237] atexit reg
2021-01-11 22:05:49,389 INFO    MainThread:16376 [wandb_run.py:_redirect():1104] redirect: SettingsConsole.WRAP
2021-01-11 22:05:49,389 INFO    MainThread:16376 [wandb_run.py:_redirect():1135] Wrapping output streams.
2021-01-11 22:05:49,389 INFO    MainThread:16376 [wandb_run.py:_redirect():1151] Redirects installed.
2021-01-11 22:05:58,338 INFO    MainThread:16376 [wandb_run.py:_atexit_cleanup():1207] got exitcode: 1
2021-01-11 22:05:58,338 INFO    MainThread:16376 [wandb_run.py:_restore():1179] restore
2021-01-11 22:05:58,338 INFO    MainThread:16376 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "7341fb77813746c5b303847de29ce8ab"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 1018
      total_bytes: 1018
    }
  }
}

2021-01-11 22:06:00,350 INFO    MainThread:16376 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "3fc316b223c5429b9317e0193490fb6f"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 4327
      total_bytes: 4327
    }
  }
}

2021-01-11 22:06:02,353 INFO    MainThread:16376 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "499a8cf7d06f4859bbf7c566475c1d48"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 4327
      total_bytes: 4327
    }
  }
}

2021-01-11 22:06:03,448 INFO    MainThread:16376 [wandb_run.py:_show_files():1536] logging synced files
2021-01-11 22:06:03,448 INFO    MainThread:16376 [internal.py:handle_exit():138] Internal process exited
